### ISSUE TITLE
Add "nowrap" option to column

### ISSUE THREAD

**Issue by Konafets** [spatie/vue-table-component#104]
It would be a nice feature to have the `nowrap` option available in a column. In my case I have an `Action` column with two buttons. The buttons breaks when the table does not fit the width.

`table-column(label="Actions", :nowrap="true")`

**Comment by sebastiandedeyne** [comment]
Why should this be declared with html/js? Isn't it a better idea to use css for this?

**Comment by Konafets** [comment]
Well, its a table property. Why should I use CSS if HTML handle this already?

**Comment by sebastiandedeyne** [comment]
It's deprecated since html5 in favor of css.

https://www.w3schools.com/tags/att_td_nowrap.asp
