### ISSUE TITLE
Incompatability with Browserify without registering components

### ISSUE THREAD

**Issue by darrenjennings** [spatie/vue-table-component#106]
Steps to reproduce:

1. `vue init browserify my-app-name`
2. cd my-app-name
3. yarn install
4. yarn add vue-table-component
5. Add this to main.js:
```js
import TableComponent from 'vue-table-component';

Vue.use(TableComponent);
```

6. Run `yarn build`

Output
```bash
yarn run v1.3.2
warning ../../../package.json: No license field
$ cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o dist/build.css ] -e src/main.js | uglifyjs -c warnings=false -m > dist/build.js
Error: Cannot find module '../helpers' from '/Users/darrenjennings/source/repos/vue-table-browserify/node_modules/vue-table-component/dist'
    at /Users/darrenjennings/source/repos/vue-table-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/darrenjennings/source/repos/vue-table-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/darrenjennings/source/repos/vue-table-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/darrenjennings/source/repos/vue-table-browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
✨  Done in 1.87s.
```

I had a similar issue in my project, https://github.com/Educents/vue-autosuggest/issues/18. I resolved it by switching to rollup, but would love to know if you guys have a better suggestion for compatibility with bundling via webpack!

**Comment by sebastiandedeyne** [comment]
Not really a Browserify user so not sure what's up.

This package is distributed as a UMD package, would a different format help?

Maybe importing `vue-table-component/src` would do the trick?

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy or use one of the many alternatives.
