### ISSUE TITLE
It'd be cool if we can add vue components into cells

### ISSUE THREAD

**Issue by taozhaolib** [spatie/vue-table-component#107]
In stead of rendering innerHtml all the time. In my case, I want to render a cell of link, in which I'd prefer use router-link instead of simple hyperlink, but the problem is vue components won't work within direct html rendering. Please let me know if there is any alternative way to do this.

**Comment by taozhaolib** [comment]
Is this the way below to use native Vue components for comlumns?

<table-column label="" :sortable="false" :filterable="false">
         <template scope="row">
             <router-link :to="somewhere" ></router-link>
         </template>
 </table-column>

**Comment by sebastiandedeyne** [comment]
Yep, that's how it's done! You have full control of the contents you want to render there :)
