### ISSUE TITLE
Is there any way to dynamically add templates/components to the vue table columns?

### ISSUE THREAD

**Issue by taozhaolib** [spatie/vue-table-component#108]
Thank you for the reply to my previous question https://github.com/spatie/vue-table-component/issues/107. I really like your veutable because it is very lightweight and easy to use by new Vue learners like me.

Here is another issue: I want to have a generic vuetable that can be adapted for any kind of data. So I want to put there some configurations so that the columns can add dynamically any kinds of components or templates based on the data settings. For example, I may want a column to have a ```<router-link>``` for this data, but next time for another set of data, I want a column that contains a ```<my-customized-template>```. Would you please give us an example how to achieve this, if possible? 

Thanks a lot.

**Comment by taozhaolib** [comment]
I wonder how ```return createElement('td', data, props.column.template(props.row.data))``` in TableCell.vue works to render the data by calling the template function. Could you show me some doc about the template() function?

**Comment by Lloople** [comment]
Hi @taozhaolib ,

I'm doing similar to what you described

    <table-column v-for="column in columns"
            :show="column.show"
            :label="column.label"
            :header-class="column.headerClass"
            :cell-class="column.cellClass"
        >

I define a columns object in javascript and then the component uses to render the different columns.

**Comment by vahidalvandi** [comment]
hi . i use this technic but have error in syntax ! 
how i can add columns by v-for ??

**Comment by vahidalvandi** [comment]
i fixed it by add key
`			<TableColumn v-for="(column,index) in columns"  :show="column.show" :label="column.label" :key="index"></TableColumn>
`
