### ISSUE TITLE
.find function for IE11 not supported

### ISSUE THREAD

**Issue by m-bosch** [spatie/vue-table-component#112]
Hi,

It seems like IE11  doesn't support the .find function and it returns an error called: Object doesn't support property or method 'find'. 

I know spatie only supports most latest versions, but for consumers is this different as for developers i think.

Any possibility how to fix this?

**Comment by sebastiandedeyne** [comment]
`Array.find` can easily be polyfilled in your app according to MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill

There are also a few npm packages floating around

https://www.npmjs.com/package/array.prototype.find
