### ISSUE TITLE
Support for Apollo Graphql

### ISSUE THREAD

**Issue by ncjones** [spatie/vue-table-component#123]
This data table component is very nice when compared to others out there but a major drawback for me was that it is not compatible with Apollo.

Apollo mutates the data on a component directly - it does not expose a response-resolving promise like this table component expects for the "fetchServerData" callback - so there needs to be some other more flexible way to react to the filter, sort and page change events.

**Comment by sebastiandedeyne** [comment]
We're not planning on supporting this in the current major version. We might revisit this in the future though.

**Comment by mekhami** [comment]
This issue really disappointed me. I was very excited to use this component, got to the point where I'm ready to add in my Apollo API, and found out it's incompatible. Really brutal.
