### ISSUE TITLE
How to use custom sorting

### ISSUE THREAD

**Issue by faustbrian** [spatie/vue-table-component#124]
Is there some way to replace the sorting algo without having to fork the package?

The sorting is quite janky with a few data sets I tested and `_.orderBy(data, key, direction)` delivers exactly the sorting I expect so I was wondering if there is some way to tell the package to use a custom sorting method.

**Comment by faustbrian** [comment]
I am currently replacing `return this.rows.sort(sortColumn.getSortPredicate(this.sort.order, this.columns));` with `return _.orderBy(this.rows, (row) => (row.data[sortColumn.show]), this.sort.order);` here https://github.com/spatie/vue-table-component/blob/master/src/components/TableComponent.vue#L221 which requires me to have a local copy of the package.

**Comment by faustbrian** [comment]
An easy solution I quickly played with would be the following.

*settings.js*
```js
const settings = {
    sortHandler: (rows, column, order) => {
        return _.orderBy(rows, (row) => (row.data[column]), order);
    }
};
```

*TableComponent.vue*

```js
if (settings.sortHandler typeof Function) {
    return settings.sortHandler(this.rows, sortColumn.show, this.sort.order);
}

return this.rows.sort(sortColumn.getSortPredicate(this.sort.order, this.columns));
```

**Comment by Lloople** [comment]
Looks like a clean and nice solution. Have you tried making a PR for that?
