### ISSUE TITLE
Data not updating on change

### ISSUE THREAD

**Issue by benwiley4000** [spatie/vue-table-component#13]
I'm quite new to Vue so this could be user error, but in the Vue dev tools I can see that my table data  prop has updated following an async fetch, yet the data doesn't update in the view. If I wait to initialize Vue until the fetch has completed, all works fine.

I'm wondering if this is because rows seem to be created [only on `mounted`](https://github.com/spatie/vue-table-component/blob/master/src/components/TableComponent.vue#L148) and should also be re-computed on the [`updated` hook](https://vuejs.org/v2/api/#updated) (or perhaps [`beforeUpdate`](https://vuejs.org/v2/api/#beforeUpdate)?

**Comment by freekmurze** [comment]
Yea, probably row creation should be triggered when the `rows` prop changed. Feel free to send a PR to correct this.

**Comment by bobbybouwmann** [comment]
A work around for this is using `v-if`. If you load your data first and then only show the table when the data is available the table will be rendered correctly
```
<table-component
                :data="users"
                show-filter="false"
                sort-by="created_at"
                sort-order="desc"
                v-if="users.length > 0"
>
    // Your table-column here
</table-component>
```
