### ISSUE TITLE
Filter the table externally

### ISSUE THREAD

**Issue by motatoes** [spatie/vue-table-component#130]
Hi! Is it possible to filter the data table externally by calling its methods? Suppose I have:

```
<table-component ref="leaderboard" ... >

</table-compenent>
```

In my script, I want to do something like:

```
this.$refs.leaderboard.setFilter('abc')
```

Is it possible to achieve this?

**Comment by tonila** [comment]
Yes! This seems to work.

```
this.$refs.leaderboard.filter = 'abc'
```
