### ISSUE TITLE
Table breaks on IE11 when filter is active

### ISSUE THREAD

**Issue by viezel** [spatie/vue-table-component#131]
The table is not shown in IE11 if show-filter is true. It works fine in any other browser. 

```html
<table-component :data="{{ $data }}" :show-filter="true">
```

This is also the case for the demo page: http://vue-table-component.spatie.be/ 

I have not found the reason atm this moment, still trying to debug why. It seems that IE11 filters all the data, so we end up with "There are no matching rows"

It might be the includes method that is not supported by IE, https://github.com/spatie/vue-table-component/blob/master/src/classes/Row.js#L58

@sebastiandedeyne any idea ?

**Comment by sebastiandedeyne** [comment]
It's probably that, should be solved by adding an `Array.includes` polyfill to your project.

**Comment by viezel** [comment]
@sebastiandedeyne yep, thats it. you would be open to im doing PR to fix this? So this components works out of the box. 

changing the **Row.js line 58**  to: 

```js
.filter(filterableValue => filterableValue.indexOf(filter.toLowerCase()) >= 0)
```
