### ISSUE TITLE
Custom pagination classes

### ISSUE THREAD

**Issue by SamuelNitsche** [spatie/vue-table-component#137]
First of all, thanks for this nice component! I haven't seen a possibility to overwrite the default css classes for pagination. Is this just not possible or did I miss something?
Thanks!

**Comment by mohitpanjwani** [comment]
Yeah Even I'm looking for a way to change the default pagination classes. Can't seem to find a way :(

**Comment by ddevdreamer** [comment]
Pagination component doesn't have a named slot like tfoot. I couldn't find a way to customize the visual of Pagination. Any suggestions please?

**Comment by benedict-w** [comment]
+1
