### ISSUE TITLE
Add class to selected row

### ISSUE THREAD

**Issue by tschaefermedia** [spatie/vue-table-component#139]
Hello, 

I need to identify a row which has been clicked. I tried the implementation from #100 but this as not changed anything and has not added a class to the clicked `<tr>` element. 

My component looks like:
```
<table-component
:data="this.runs.results"
sort-by="id"
sort-order="asc"
:show-caption=false
v-on:rowClick="rowClicked"
:row-class="highlight"
>
```
And the added methods are doing defined as:
```
highlight(row) {
    if (row.data) return this.highlightedRow === row.data.vueTableComponentInternalRowId ? 'highlight' : '';
    return '';
},
rowClicked(row) {
    this.expand = false;
    this.log = eval('`' + this.runs.results[row.data.id].logFile + '`');
},
```
Does there is a way to add a class to a selected row? Or does I'm doing something wrong here?

**Comment by ywuliu** [comment]
Hi, how is it going? any thing new?

**Comment by CILP** [comment]
@ywuliu @tschaefermedia I found myself in the same problem, so I did the following:

`<table-component @rowClick="setSelected" :data="someData" :show-caption="false" :show-filter="false" class="table-class text-center">`

I used the @rowClick event in the next way:

data () {
 return { 
   selected: {},
   headers: [
        { show: 'name', label: 'Name', dataType: '' },
        { show: 'price', label: 'Price', dataType: 'numeric' },
        { show: 'some', label: 'Some', dataType: 'numeric' }
      ],
 }
}

in methods:

methods: {
    setSelected (s) {
      this.selected = {...s.data}
      ...
    }
  }

And I defined table columns in the next way

`<table-column ref="table" v-for="h in headers" :key="h.show" :show="h.show" :label="h.label" :data-type="h.dataType">
    <template slot-scope="row">
      <span :class="{'is-active': selected.name === row.name}">{{row[h.show]}}</span>
    </template>
  </table-column>`

in CSS:

`.table-class table tbody tr td span.is-active {
   color: red;
}`

and there is :) 
it's not the better but, I hope can help you guys.

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy or use one of the many alternatives.
