### ISSUE TITLE
'sort-by' only works for rendered columns

### ISSUE THREAD

**Issue by benwiley4000** [spatie/vue-table-component#14]
The column `sort-by` prop fails if I try to sort by a data property that isn't being shown in a column. It should probably still work for data that is hidden.

**Comment by freekmurze** [comment]
The tests seem to indicate that this is working properly:
https://github.com/spatie/vue-table-component/blob/master/__tests__/components/table-component/sort.test.js#L85-L110

**Comment by benwiley4000** [comment]
You may have misunderstood. In that example the songs column is rendered. I'm saying let's say your data looks like this:

```js
{ date, formattedDateString, name }
```

And you only want to render the `formattedDateString` and `name` columns but order `formattedDateString` by `date` which isn't even a column.

**Comment by freekmurze** [comment]
Fixed by #19
