### ISSUE TITLE
vue-table-component@1.9.1" has unmet peer dependency "moment@^2.18.1

### ISSUE THREAD

**Issue by binobose** [spatie/vue-table-component#141]
vue-table-component@1.9.1" has unmet peer dependency "moment@^2.18.1". Can anyone please help to resolve this issue asap.

![error](https://user-images.githubusercontent.com/10970818/37425827-b3c77cbc-27bc-11e8-83f4-60e0d37b7905.png)

**Comment by sebastiandedeyne** [comment]
This is not an issue with the package. You need to install `moment` yourself, that's why it's declared as a `peerDepencdency`.

See https://nodejs.org/en/blog/npm/peer-dependencies/
