### ISSUE TITLE
Sorting a column with numbers sorts alphabetically instead of numerically

### ISSUE THREAD

**Issue by dick-ey** [spatie/vue-table-component#145]
Given the dataset: `[ 9, 9812, 945, 10000]`
 - When sorting a column with these values and  `sort-order` set to `desc`, it will display the numbers in the following order: `[9812, 945, 9, 10000]`
This is likely because all sortables are passed as type: string. Expected behavior is to return numerically sorted values:
 `[10000, 9812, 945, 9]`

**Comment by manoreaumarois** [comment]
Did you use data-type="numeric"?
https://github.com/spatie/vue-table-component#props

**Comment by dick-ey** [comment]
I must have missed that in the docs. Thank you!
