### ISSUE TITLE
table component filter autofocus

### ISSUE THREAD

**Issue by 4moradi** [spatie/vue-table-component#147]
First of all, thanks for this nice component!
How is it possible to add autofocus to input filter of table?
And one more question, how can I select the string automatically after enter something to filter?

Thanks a lot

**Comment by sebastiandedeyne** [comment]
Autofocus isn't possible out of the box. You could achieve it by writing some custom JavaScript outside of the component.

What do you mean by selecting the string? If you mean highlighting the result, that's outside of the scope of this package.
