### ISSUE TITLE
Per-row click listener support

### ISSUE THREAD

**Issue by benwiley4000** [spatie/vue-table-component#15]
I would be nice to have event listener support for row clicks, which could be pre-set as data properties.

**Comment by freekmurze** [comment]
If this is something that is easily implemented and easy to tests, I'd accept that as a PR.

**Comment by sebastiandedeyne** [comment]
Tempted to add an `@click` event to the table component, which would have column, row and row data in it's payload. Not sure what the behaviour should be when clicking something like the filter though.

**Comment by benwiley4000** [comment]
Seems to me like it should only be for the actual table rows, not the
heading.

On Jun 26, 2017 4:10 AM, "Sebastian De Deyne" <notifications@github.com>
wrote:

Tempted to add an @click event to the table component, which would have
column, row and row data in it's payload. Not sure what the behaviour
should be when clicking something like the filter though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spatie/vue-table-component/issues/15#issuecomment-310991785>,
or mute the thread

**Comment by freekmurze** [comment]
> Tempted to add an @click event to the table component

We'd accept a PR that adds this to the package.

**Comment by benwiley4000** [comment]
@sebastiandedeyne maybe you could just give the table a general `onFilter` callback or something, but individual cell-level click callbacks for the filter headings seems unnecessary, since they are pretty single-responsibility.

**Comment by aboustayyef** [comment]
I came here because I'm trying to add a link in one of the columns (an "edit" link for row of data that would take me straight to my record editing route in laravel), but from reading around, it seems this is not possible at the moment. Correct?

**Comment by sebastiandedeyne** [comment]
You can do that with a scoped slot or a formatter function.

https://github.com/spatie/vue-table-component#formatting-values

**Comment by pieterjandesmedt** [comment]
Added PR #80

**Comment by GreggOrdHume** [comment]
@pieterjandesmedt @sebastiandedeyne 

I know you will be updating the docs soon but for now how do we make use of this click event and access it in Vue ? An example would be helpful :)

Thanks

**Comment by sebastiandedeyne** [comment]
You can listen to the `@rowClick` event on the table component. The event payload will be the row's data.

```html
<table-component
    ...
    @rowClick="handleRowClick"
></table-component>
```

**Comment by erwin16** [comment]
I tried it .. but  does not work for me ...

		<template>
		  <div id="users" class="container">
		    <table-component :data= "fetchData" ref="table" @rowClick="handleRowClick" sort-by="songs" sort-order="asc">
		        <table-column show="id" label="ID" data-type="numeric" hidden></table-column>
		        <table-column show="firstName" label="First name"></table-column>
		        <table-column show="lastName" label="Last name"></table-column>
		        <table-column show="email" label="Email"></table-column>
		        <table-column show="birthday" label="Birthday" data-type="date:DD/MM/YYYY"></table-column>
		        <table-column show="isAdmin" label="Is Admin?"></table-column>
		        <table-column label="" :sortable="false" :filterable="false">
		            <template slot-scope="row">
		                <a :href="`#${row.id}`">Edit</a>
		            </template>
		        </table-column>
		    </table-component>
		  </div>
		</template>

		<script>
		import axios from 'axios'
		import store from '@/vuex/store'
		import { mapActions } from 'vuex'
		import _ from 'underscore'
		export default {
		  name: 'UsersPage',
		  methods: _.extend({}, mapActions(['userCount']), {
		    async fetchData ({ page, filter, sort }) {
		      const response = await axios.get('users', { params: { _page: page, _sort: sort, _limit: 5 } })
		      const pages = Math.ceil(store.state.userCount / process.env.MAX_USER_PER_PAGE)
		      response.pagination = { currentPage: page, totalPages: pages }
		      return response
		    },
		    handleRowClick: function (payload) {
		      console.log('ROW CLICKED')
		    }
		  }),
		  store,
		  mounted: function () {
		    this.$nextTick(function () {
		      this.userCount()
		      this.$refs.table.refresh()
		    })
		  }
		}
		</script>

**Comment by sebastiandedeyne** [comment]
You're definitely on the latest version of the package?

I'll give this a look this week.

**Comment by GreggOrdHume** [comment]
I can confirm @rowClick is not working for me.
`"vue-table-component": "^1.8.0"`

```
import TableComponent from 'vue-table-component';
Vue.use(TableComponent);
new Vue({
  el: '#app',
  data: {...},
  methods:{
    handleRowClick: function(){
      console.log('row clicked');
    },
  }
});
```

**Comment by pieterjandesmedt** [comment]
That's strange, it is working for me with the same versions of vue and vue-table-component. Maybe try a `rm -rf node_modules`, `rm package-lock.json` and `npm i`?

**Comment by GreggOrdHume** [comment]
I had high hopes for this. Dropped the node_modules folder, no package-lock.json, re-installed all modules and no luck.

**Comment by pieterjandesmedt** [comment]
I just did the same and it's still working for me. Maybe the `<a>` is interfering somehow?

**Comment by GreggOrdHume** [comment]
No its not that.

If i watch my webpack modules it reads `node_modules/vue-table-component/dist/index.js`
If i edit the method in there and add a console log to the emitRowClick like this, it console logs the row on click:
```
emitRowClick: function emitRowClick(row) {
  console.log(row);
  this.$emit('rowClick', row);
}
```

So it seems that the row click is happening and the listener is on but how do I access it in my Vue?

**Comment by pieterjandesmedt** [comment]
Try importing the TableComponent 'locally':

**Comment by GreggOrdHume** [comment]
Im not sure what you mean, something like this?
import TableComponent from 'node_modules/vue-table-component/dist/index.js';

**Comment by pieterjandesmedt** [comment]
Or try
`import { TableComponent } from 'vue-table-component';`
instead of
`import TableComponent from 'vue-table-component';`

**Comment by GreggOrdHume** [comment]
Doesnt work:
```
import Vue from 'vue';
import { TableComponent, TableColumn } from 'vue-table-component';

Vue.component('table-component', TableComponent);
Vue.component('table-column', TableColumn);
```

**Comment by pieterjandesmedt** [comment]
Try converting your app to use [single file components](https://vuejs.org/v2/guide/single-file-components.html)... after that, I'm out of suggestions :-/

**Comment by GreggOrdHume** [comment]
I think my limited knowledge in Vue has lightened me to the fact that i: a) need to learn Vue properly... and b) should probably write my own components to get a better understanding of them.

Thanks for helping out and all the suggestions.

**Comment by vahidalvandi** [comment]
rowClick not defined !!
