### ISSUE TITLE
Override filter input element and reset button template HTML

### ISSUE THREAD

**Issue by veturi** [spatie/vue-table-component#153]
I didn't find any information about this so asking here: is it possible to override the default filter input element and reset button template HTML in a similar manner it is possible to define custom template for a table row?

Possible use case is to for example modify the filter input to adhere to bootstrap HTML format. If this not already doable I'll write it and send a pull request.

**Comment by marcoapferegrino** [comment]
Hello Any solution ?? I guess filter should be able to customize it
