### ISSUE TITLE
Pagination is showing but not working

### ISSUE THREAD

**Issue by VerzatileTom** [spatie/vue-table-component#156]
I managed to make the pagination appear but it seems to do nothing. It doesn't seem to trigger a data change in the table. How can I make this happen? Thanks in advance!

**Comment by piyushbeli** [comment]
I do have the same issue.

**Comment by projct1** [comment]
Same issue, pagination works wrong!
http://skrinshoter.ru/s/201018/JAeGPgkf
http://skrinshoter.ru/s/201018/hfCgeV6G
etc...

**Comment by projct1** [comment]
I am disappointed, because it is spatie...

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy or use one of the many alternatives.
