### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by espositodaniele** [spatie/vue-table-component#166]
## Installation failed

Hello, I'm just trying to install this package following the instructions: 

```bash
npm install vue-table-component --save
```

Next, you must register the component. The most common use case is to do that globally.

```js
//in your app.js or similar file
import Vue from 'vue';
import { TableComponent, TableColumn } from 'vue-table-component';

Vue.component('table-component', TableComponent);
Vue.component('table-column', TableColumn);
```
then when I compile with webpack I got this error: 

```bash
WARNING in ./resources/assets/js/bootstrap.js
63:33-47 "export 'TableComponent' was not found in 'vue-table-component'
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

WARNING in ./resources/assets/js/bootstrap.js
64:30-41 "export 'TableColumn' was not found in 'vue-table-component'
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```
Anyone can help me with this? 

Thanks :+1:

**Comment by ShaneShipston** [comment]
I assume you inadvertently downloaded the alpha version that was just published to NPM try using `npm install vue-table-component@1.9.1 --save` instead

**Comment by espositodaniele** [comment]
Yes, I've done that already and forgot to close the issue. Thanks anyway @ShaneShipston :+1:

**Comment by benedict-w** [comment]
I had this issue after the fix above I'm now getting:

ERROR in ./node_modules/vue-table-component/dist/index.js
Module not found: Error: Can't resolve 'moment' in '/app/node_modules/vue-table-component/dist'
 @ ./node_modules/vue-table-component/dist/index.js 3:27-44
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

Any ideas?
