### ISSUE TITLE
[Improvement] Remove dependency on moment

### ISSUE THREAD

**Issue by abhipanda** [spatie/vue-table-component#168]
Ref: https://github.com/spatie/vue-table-component/issues/148

Momentjs had its moment now its time to move on to smaller and tree shaking compatible library like
https://date-fns.org/

Evidently the only code which is being used is format

```
   if (dataType.startsWith('date')) {
            const format  = dataType.replace('date:', '');
           return moment(value, format).format('YYYYMMDDHHmmss');
    }
```
Its a drop in replacement with 500KB savings :)

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy or use one of the many alternatives.
