### ISSUE TITLE
Sorting arrow

### ISSUE THREAD

**Issue by bobbybouwmann** [spatie/vue-table-component#17]
Hi,

I was thinking about sending a PR which adds a sorting arrow next to the column for the current sorted column. We can add an option to enable or disable it of course.

What do you think?

**Comment by freekmurze** [comment]
The component already applies some classes with which you can determine the current order.

On [the demo page](http://vue-table-component.spatie.be/) you can see an example where we added arrows next to the column being sorted.

**Comment by bobbybouwmann** [comment]
Aah great, didn't know! Thanks for pointing out :D
