### ISSUE TITLE
I just found this and wondering if I should start with V1 or V2? 

### ISSUE THREAD

**Issue by jamesgibson14** [spatie/vue-table-component#170]
Is V2 far enough along to start using it? is the Api the same?

**Comment by sebastiandedeyne** [comment]
We started v2, but it's never gonna see the light of day. In the near future, this package will be deprecated in favor of a new one: vue-data-component https://github.com/spatie/vue-data-component

v1 will still get bugfixes if necessary, but we won't be adding any more new features.
