### ISSUE TITLE
formatter as mixins

### ISSUE THREAD

**Issue by juanbrujo** [spatie/vue-table-component#172]
I have many formatters but imported as mixins (used many times in many components). Cannot use them with `:formatter` is there any way to recycle them? Or I have to copy in the new view and duplicate the code?

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy or use one of the many alternatives.
