### ISSUE TITLE
Combine template slot and :formatter

### ISSUE THREAD

**Issue by juanbrujo** [spatie/vue-table-component#173]
Any way to make this work?

```
<table-column show="state" label="Estado" :formatter="formatState">
  <template slot-scope="row">
    {{ row.state }}
  </template>
</table-column>
```

Now I'm:

```
<table-column show="state" label="Estado">
  <template slot-scope="row">
    {{ formatState(row.state) }}
  </template>
</table-column>
```

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy or use one of the many alternatives.
