### ISSUE TITLE
Support pagination

### ISSUE THREAD

**Issue by DannyFeliz** [spatie/vue-table-component#18]
Hi, 

I was wondering if you are planning to support pagination?
Maybe something like this [vuejs-uib-pagination](https://plnkr.co/edit/hcfYWCTaQ7GnlO7AitGM?p=preview)

BTW awesome component

**Comment by freekmurze** [comment]
Thanks for the kind words on this package :-)

Currently there are no plans for pagination. I'm going to keep this component as simple as can be.
