### ISSUE TITLE
Click event on buttons in table

### ISSUE THREAD

**Issue by bobbybouwmann** [spatie/vue-table-component#23]
Hi,

Quick question: is it possible to add an on-click event to one of the generated TableRows. Let's say you have a edit button you would expect to have a way to call a method for the onclick instead of just putting in a general a:href link. 

I basically need to find a way to make the data so that VueJs understands that when I click on a button in the table it performs some kind of action. 

Below example is always rendered as a normal string and therefor the event is not useable. 
```
'<a title="Verwijderen" @click="alert"><i class="fa fa-fw fa-trash-o"></i></a>'
```

Let me know if you have a solution for this. Maybe I'm missing something or maybe this functionality doesn't exist yet.

**Comment by sebastiandedeyne** [comment]
We just added support for scoped slots in `table-column`. It's not tagged yet, but should be available by tomorrow. You'll be able to declare your own cell template then.

Our demo page has an example of an edit url! https://github.com/spatie/vue-table-component/blob/4d16dd3cff1601f6a76e93d9a07bafa1b4b9a6a2/docs/index.html#L149

**Comment by bobbybouwmann** [comment]
Thanks :D
