### ISSUE TITLE
Different data

### ISSUE THREAD

**Issue by Budy-Love** [spatie/vue-table-component#33]
Hello,

it's possible to add another data or string to table-column? For example

`<table-column show="myFirstData" label="First data"></table-column>`
`<table-column show="mySecondData" label="Second data" ></table-column>` or
`<table-column show="someText" label="Some text" ></table-column>`

`  export default{
    data () {
      return {
       myFirstData: [],
       mySecondData: [],
       someText: 'whoops'
    }
`

**Comment by sebastiandedeyne** [comment]
You an pass a formatter to the column to transform the data in the row. This is a new feature, so you might need to update your dependencies first!

https://github.com/spatie/vue-table-component#formatting-values

**Comment by Budy-Love** [comment]
Excactly what i need. Thanks in advance.
