### ISSUE TITLE
TableCell lost v-html in 1.4

### ISSUE THREAD

**Issue by Budy-Love** [spatie/vue-table-component#35]
Hello again,

sorry for annoying you. I use the formatter function to build links in my table like

![screen shot 2017-08-11 at 16 05 29](https://user-images.githubusercontent.com/10800984/29216442-00c48922-7eaf-11e7-9762-fe7c1701eea6.png)

results in:

![screen shot 2017-08-11 at 16 05 47](https://user-images.githubusercontent.com/10800984/29216441-00c024f4-7eaf-11e7-8060-057f3dbc8199.png)

It's possible to bring back the old v-html behaviour that will not escape raw html?

Thanks in advance!

budy

**Comment by sebastiandedeyne** [comment]
Gonna look into reimplementing this in 1.4 next week.

In the mean time, the recommended way to do this is now a custom column template.

https://github.com/spatie/vue-table-component/blob/01c938cc159ebd54b8a176fea9f432bb8e942ba8/docs/index.html#L149

**Comment by Budy-Love** [comment]
I really like the custom column template, easier than the formatter. So there is is no longer an issue for me :-)

**Comment by sebastiandedeyne** [comment]
In case anyone still needs it, html formatters are re-enabled.
