### ISSUE TITLE
component cannot render text with white spaces

### ISSUE THREAD

**Issue by efriedli** [spatie/vue-table-component#38]
Hi there, pretty amazing and lightweight work!
Is there a way to render a string that contains white spaces (or any other special character, for that matter) in your awesome vue-table-component?
To reproduce the issue: in your demo, go from the working row:
```
data="[
{ firstName: 'John', lastName: 'Lennon', instrument: 'Guitar',
editUrl: '<a href='#john'>Edit</a>', birthday: '04/10/1940', songs: 72 }]"
```
to this non-working row (John becomes Joh n):
```
data="[
{ firstName: 'Joh n', lastName: 'Lennon', instrument: 'Guitar',
editUrl: '<a href='#john'>Edit</a>', birthday: '04/10/1940', songs: 72 }]"
```

**Comment by efriedli** [comment]
Nevermind, for some reason I don't entirely understand :) moving from :data={{ $data }} to :data="{{ $data }}" solved my problem.

**Comment by sebastiandedeyne** [comment]
In html that would render to `<element data="Joh" n></element>`, which means `n` would be an attribute of it's own :)

**Comment by efriedli** [comment]
got it, thanks!
