### ISSUE TITLE
Some way to raise events for each row

### ISSUE THREAD

**Issue by amitavroy** [spatie/vue-table-component#4]
There should be a way to raise events or handle click events for each row. Many times clicking on a table row would trigger an event. Would be very nice to have such a feature. 

Just a call back function or on click of row, $emit with the name of event and the data to pass.

**Comment by freekmurze** [comment]
I'd accept a PR with tests that adds this the package.

**Comment by sebastiandedeyne** [comment]
Gonna close this because #15 is similar. Please move all further discussion there.
