### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by lmatab** [spatie/vue-table-component#40]
Hello Spatie Team, thanks a lot for sharing this nice component. 

I'm using laravel spark and I have installed it successfully  vue-table-component.

Although when I try to use it with the Retrieving data asynchronously feature  it just does not work, the page get blank and the console says:Uncaught ReferenceError: "regeneratorRuntime is not defined", I guess it has something to do with the async and wait commands in the fetchdata function.

I am just learning vue.

I appreciate your feedback.

**Comment by sebastiandedeyne** [comment]
I think there's something wrong with our build step then. I'll look into fixing this early next week!

**Comment by sebastiandedeyne** [comment]
If your're running into this issue, please include the `babel-regenerator-runtime` package in your application.

https://www.npmjs.com/package/babel-regenerator-runtime

Gonna hold off on shipping it with the package for now, because it would result into lots of duplicate code in people's apps. If anyone has thoughts on this, feel free to discuss!

**Comment by sebastiandedeyne** [comment]
I made some changes on this front. If anyone could let me know if `1.4.1` is an improvement, would be great!

**Comment by bmadigan** [comment]
Just added this component and then ran into this Issue (regeneratorRuntime is not defined) 

- So I ran `yarn add babel-regenerator-runtime` and still got the same error.
- I then `rm -rf node_modules` and reran `yarn` and still the same error above.

**Comment by ttomdewit** [comment]
@bmadigan Did you add `require('babel-regenerator-runtime');` to your JavaScript file? That solved the console error for me just now.
