### ISSUE TITLE
Styling not showing on component

### ISSUE THREAD

**Issue by cringer** [spatie/vue-table-component#42]
I might just be missing the obvious but I can't figure out how to get styling on the component.  I was hoping that once installed it would look like the demo.  Functionality seems to work fine, it just looks ugly as hell.

![vue-table](https://user-images.githubusercontent.com/835448/29641988-24b7606e-881b-11e7-9bcf-3957b1fcc843.PNG)

**Comment by maorbote** [comment]
This component does not has any style by default.
In the [live demo](http://vue-table-component.spatie.be/), it has external style sheet.

You may

1. Copy the css file form demo
2. Write your own style


cheers
