### ISSUE TITLE
Show combined column data under one TableColumn

### ISSUE THREAD

**Issue by rgb-one** [spatie/vue-table-component#49]
Lets say the object we pass to the `TableComponent` has a `first_name` and `last_name` attribute, however we only want to `show` the combined `first_name` and `last_name` under the label "Name". Can this be done?

**Comment by sebastiandedeyne** [comment]
In the latest version, you could either use a custom column template, or a formatter function. Both are explained in the docs right here: https://github.com/spatie/vue-table-component#formatting-values

**Comment by rgb-one** [comment]
Ah, awesome, saw that part of the code but I just looked at it, didn't know what was going on. Thanks.
