### ISSUE TITLE
Custom table columns don't appear to be filterable

### ISSUE THREAD

**Issue by rgb-one** [spatie/vue-table-component#55]
Custom `TableColumn`'s don't appear to be filterable even when `:filterable="true"` is set. How can I filter a custom `TableColumn`?

**Comment by sebastiandedeyne** [comment]
Could you post a code snippet of where it's going wrong, together with actual and expected behaviour?

**Comment by sebastiandedeyne** [comment]
Gonna close this for now, feel free to reopen if you're still having issues!
