### ISSUE TITLE
Refresh Data

### ISSUE THREAD

**Issue by scortes1989** [spatie/vue-table-component#56]
How can refresh/update data at store/update/delete in a crud example ?

**Comment by sebastiandedeyne** [comment]
Vue is reactive, so if you change whatever's in the `data` prop, it should refresh.

If this isn't working, please provide a code snippet or a broken test for us to debug with.

**Comment by scortes1989** [comment]
Sorry by my bad explanation.

I was refering to usage async method for load data:

https://github.com/spatie/vue-table-component#retrieving-data-asynchronously

In the component the ajax is call for the child, but i like call for the parent

`axios.post('/api/core/users', this.create)
 .then(({data}) => {
       //modify data async
})` 

Thanks !

**Comment by sebastiandedeyne** [comment]
You'll need to add a ref to your component instance, and call refresh on it.

```html
<table-component :data="fetchData" ref="table">
    <table-column show="firstName" label="First name"></table-column>
</table-component>
```

```js
axios.post('/api/core/users', this.create)
    .then(({ data }) => {
        this.$refs.table.refresh();
    });
```

**Comment by scortes1989** [comment]
Excellent !

Could you please add it to the documentation? it is something I did not know about vue.

Thanks !

**Comment by sebastiandedeyne** [comment]
Yeah was missing from the readme, added a little note about it :)
