### ISSUE TITLE
Dynamic Columns

### ISSUE THREAD

**Issue by leyluj** [spatie/vue-table-component#58]
Hello,

Could we please have dynamic column?

i.e you can configure the columns required on runtime.

**Comment by sebastiandedeyne** [comment]
Please post a code snippet of the behaviour you'd like to see. I don't see why you couldn't generate the columns template at runtime right now.

**Comment by sebastiandedeyne** [comment]
Gonna close this for now, feel free to reopen if you're still having issues!
