### ISSUE TITLE
Set Header Class

### ISSUE THREAD

**Issue by faustbrian** [spatie/vue-table-component#60]
Is there some way to set a class for the `thead` elemen? Bootstrap 4 will have classes like `<thead class="thead-default">` or `<thead class="thead-inverse">` so would be nice if that is possible.

If it's not possible I could send a PR for it.

**Comment by willemvb** [comment]
This is not available right now, but we'll accept a PR that introduces a `thead-class` prop on the `table-component`.

**Comment by faustbrian** [comment]
@willemvb https://github.com/spatie/vue-table-component/pull/61

**Comment by freekmurze** [comment]
We'll handle this further in #61
