### ISSUE TITLE
Always put undefined values at the end when sorting

### ISSUE THREAD

**Issue by neontuna** [spatie/vue-table-component#70]
Currently the sort function is returning a blank string from `getSortableValue()` when the value is undefined.

```
    getSortableValue(columnName) {
        const dataType = this.getColumn(columnName).dataType;

        let value = this.getValue(columnName);

        if (value === undefined) {
            return '';
        }
...
```

The effect of this is that undefined values get sorted ahead of everything else when sorting ascending.

I deal with data that has a lot of holes in it, and it was irritating to have null values appearing before existing values.   

It would be a pretty trivial update to the `getSortPredicate()` function to always place undefined values at the end, regardless of sorting ascending or descending.   But before writing it up and fixing tests and what not, I just wanted to make sure this is something you guys would like.

Btw I tried what seems like a dozen table components for my project before settling on this.  Its seriously awesome!

**Comment by sebastiandedeyne** [comment]
I understand the value in this, but it would currently be a breaking change...

How about adding the ability to pass a sort function to a `table-column`?

**Comment by freekmurze** [comment]
We'll handle this in a future major version.
