### ISSUE TITLE
access to row item index

### ISSUE THREAD

**Issue by ned2** [spatie/vue-table-component#72]
Is there a way to access the current index of the row that's updated based on the current sort order? I was hoping that I could just do something like `{{row.index}}` inside the template of the `table-column` component.

**Comment by sebastiandedeyne** [comment]
I'd accept a non-breaking PR that adds this.

You'd need to track the index in the for loop rendering the rows, and pass it down to the cell.

**Comment by ned2** [comment]
OK cool, I'll try and come up with something. Haven't done much vue before but this seems like it shouldn't be too hard.

**Comment by Konafets** [comment]
@sebastiandedeyne What to do with the index in the cell? Assign it to `data`?

**Comment by sebastiandedeyne** [comment]
Yeah, sounds good (in `Row.data` specifically)

**Comment by pieterjandesmedt** [comment]
Would be happy to see this as well. Is there anything blocking #96 ?

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy or use one of the many alternatives.
