### ISSUE TITLE
how to add a row if Retrieving data asynchronously

### ISSUE THREAD

**Issue by saqueib** [spatie/vue-table-component#74]
I have a CRUD setup, I am loading table from ajax, now when I add a new item I want to push some data into a table but it's not working. I need to call `this.$refs.table.refresh();` which hits the server. 

How can I `data.push(item)` into the array show it in the table?

here is my method which fetches data

```js
loadTableData(param) {
    let params  = $.param(param);

    this.tableLoading = true;
    return axios.get(this.url + '?' + params).then((res) => {

        this.tableLoading = false;
        this.result = res.data.data;

        return {
            data: this.result,
            pagination: {
                currentPage: res.data.meta.current_page,
                totalPages: res.data.meta.last_page,
                count: res.data.meta.total
            }
        }
    })
}
```

Please help, I have used this table in many places,  don't want to try some other data table 😦

**Comment by GreggOrdHume** [comment]
@saqueib : Wouldn't you update the object that the table is already using? Therefore allowing Vue to manage that?

So on your requests response you can push the new row of data to the data variable that Vue is already holding for the table.

In my opinion you **do not** need to do `this.$refs.table.refresh();`

```
new Vue({
  el: '#app',
  data: {
    tableData: [] || dataFromPageLoad
  },
  methods:{
    updateTableData: function(){
      // in your ajax response you can do
      this.tableData.push(ajaxResponseData);
    }
  }
});
```

**Comment by sebastiandedeyne** [comment]
Gonna close this issue since it looks inactive for now. Feel free to reopen if there's still a problem!
