### ISSUE TITLE
Large number of pagination links for huge data.

### ISSUE THREAD

**Issue by alexankit** [spatie/vue-table-component#75]
I'm using the latest version of the component.
The problem is that for the huge data, the components generates a large list of pagination links.

If data has 1000 records and each page having 10 records then the component generates 100 pagination links.

Is there a way to skip some pagination links from the pagination list like in the attached image?

![pagination-show](https://user-images.githubusercontent.com/10940370/32215577-59664574-be48-11e7-8f47-036b375f196b.gif)

**Comment by sebastiandedeyne** [comment]
Please refer to #48 to discuss pagination
