### ISSUE TITLE
Null value returns error

### ISSUE THREAD

**Issue by malinky** [spatie/vue-table-component#77]
A null value returns a Cannot read property 'toString' of null error. In `getSortableValue()` could we check for undefined or null? Or should I be removing null values?

`
if (value === undefined || value === null) {
  return '';
}
`

**Comment by sebastiandedeyne** [comment]
We'd accept a tested PR that fixes this

**Comment by pieterjandesmedt** [comment]
PR #99 fixes this.

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy or use one of the many alternatives.
