### ISSUE TITLE
Replace moment dependency with something more light weight

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/vue-table-component#87]

**Comment by sebastiandedeyne** [comment]
Preferably no external dependency

**Comment by hiendv** [comment]
Just want to remind you that this is a huge problem. I would choose `date-fns` over `moment`.
```js
import format from 'date-fns/format'
format(new Date(), 'YYYYMMDDHHmmss')
//=> "20171215143039"
```

But it may take a while before the new `parse` function arrives. It's in the beta release for now. https://github.com/date-fns/date-fns/issues/219

**Comment by sebastiandedeyne** [comment]
Formatting isn't an issue, it's the parsing that we need to find something for.

**Comment by hiendv** [comment]
I know. Try the alpha release:
https://date-fns.org/v2.0.0-alpha.2/docs/parse

**Comment by mekhami** [comment]
Does this have any movement? I would like to get rid of the moment dependency for something smaller.
