### ISSUE TITLE
How to combine two cols to one

### ISSUE THREAD

**Issue by Konafets** [spatie/vue-table-component#90]
I like to get a table structure like this, but I don't see a possibility in the code to do this since there is no `colspan` prop. Do you think its possible to implement that? With some hints I could like to create a PR.

Or do you have a better idea? 

```
<table>
    <thead>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col" colspan="2">Action</th>
    </thead>
    <tbody>
        <tr>
            <td>John</td>
            <td>Lennon</td>
            <td>
                <button>Edit</button>
            </td>
            <td>
                <button>Delete</button>
            </td>
        </tr>
    </tbody>
</table>
```

**Comment by sebastiandedeyne** [comment]
Hi, we currently don't support spans. I don't think we want to either for now, as it would add a lot of complexity. I'll look into this the next major version though!
