### ISSUE TITLE
Does this require async/await usage

### ISSUE THREAD

**Issue by makapaka23** [spatie/vue-table-component#95]
I cannot seem to get this to work with normal promises instead of async await (for now trying not to use babel etc).

I'm getting the error

`Uncaught (in promise) TypeError: Cannot read property 'pagination' of undefined`

Standard way I've been doing things in the method using `<table-component :data="fetchSessions">`

`
fetchSessions() {
                        axios.get(this.endpoint)
                        .then(({data}) => {
                                this.dataSession = data;
                        });
                },
`
Anything you can suggest to get it working with promises or must it use async await?

**Comment by freekmurze** [comment]
Seems like this issue is not related to this package.
